# Generated by Django 5.1.1 on 2025-07-01 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BCOFileDescriptor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bcoid", models.CharField(max_length=255)),
                ("keywords", models.JSONField(default=list)),
                ("body_sites", models.JSONField(default=list, null=True)),
                ("access_categories", models.JSONField(default=list, null=True)),
                ("files_represented", models.JSONField(default=list, null=True)),
                (
                    "usability_domain",
                    models.CharField(default="No description provided", max_length=500),
                ),
                ("db_support", models.CharField(max_length=500, null=True)),
            ],
        ),
    ]
